### ISSUE TITLE
Unable to build on MacOS

### ISSUE THREAD

**Issue by MrChico** [kframework/wasm-semantics#78]
Not sure whether I'm missing some deps. I was able to do the opam stuff successfully – might be something with the KNinja stuff. Did anyone else experience this?

Running `./build` yields
```
Traceback (most recent call last):
  File "./build", line 72, in <module>
    proj.main()
  File "./.build/kninja/__init__.py", line 258, in main
    os.execlp('ninja', 'ninja', '-f', self.builddir('generated.ninja'), *remaining)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 554, in execlp
    execvp(file, args)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 571, in execvp
    _execvpe(file, args)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 613, in _execvpe
    raise last_exc
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 604, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by hjorthjort** [comment]
Not sure if relevant (I got a different error message) but when I tried to build a few days ago for the first time in a month or so I had to manually do `opam switch 4.06.1+k`. For some reason, I was still at `4.03.1+k`, even after doing `make clean; make deps; ./build`.

**Comment by MrChico** [comment]
Looks like I missed installing ninja. This is no longer an issue. Thanks
